---
board:
  size: 15
bag:
  letters:
    a:
      bag_amount: 9
      point_val: 1
    b:
      bag_amount: 2
      point_val: 3
    c:
      bag_amount: 2
      point_val: 3
    d:
      bag_amount: 4
      point_val: 2
    e:
      bag_amount: 12
      point_val: 1
    f:
      bag_amount: 2
      point_val: 1
    g:
      bag_amount: 3
      point_val: 2
    h:
      bag_amount: 2
      point_val: 4
    i:
      bag_amount: 9
      point_val: 1
    j:
      bag_amount: 1
      point_val: 8
    k:
      bag_amount: 1
      point_val: 5
    l:
      bag_amount: 4
      point_val: 1
    m:
      bag_amount: 2
      point_val: 3
    n:
      bag_amount: 6
      point_val: 1
    o:
      bag_amount: 8
      point_val: 1
    p:
      bag_amount: 2
      point_val: 3
    q:
      bag_amount: 1
      point_val: 10
    r:
      bag_amount: 6
      point_val: 1
    s:
      bag_amount: 4
      point_val: 1
    t:
      bag_amount: 6
      point_val: 1
    u:
      bag_amount: 4
      point_val: 1
    v:
      bag_amount: 2
      point_val: 4
    w:
      bag_amount: 2
      point_val: 4
    x:
      bag_amount: 1
      point_val: 8
    y:
      bag_amount: 2
      point_val: 4
    z:
      bag_amount: 1
      point_val: 10
    blank:
      bag_amount: 2
      point_val: 0
test:
  bag:
    letters:
      c:
        bag_amount: 10
        point_val: 3
      a:
        bag_amount: 10
        point_val: 1
      t:
        bag_amount: 10
        point_val: 1
    word: 'CAT'